# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Deploy

permissions:
  contents: write

on:
  push:
    tags:
      - "**"

jobs:
  extension_bundle:
    name: Extension Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - name: Install Dependencies
        run: |
          sudo apt install extra-cmake-modules kwin-dev qt6-base-dev
      - name: Create Release
        run: |
          cmake -S . -B build
          cmake --build build --config Release
      - name: Upload Release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de #v2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/kwin/effects/plugins/kandointegration.so
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
